### ISSUE TITLE
Exposed API key

### ISSUE THREAD

**Issue by Educorreia932** [pmcdonough8133/last.timer#11]
Be careful, as the API key is hardcoded in the request calls

**Comment by pmcdonough8133** [comment]
I always meant to getting around to that but forgot and didn't care enough at first. Finally took the time to fix. Thanks

**Comment by pmcdonough8133** [comment]
Apparently I never cleared cache when I checked this so I didn't catch it breaking the live site

**Comment by pmcdonough8133** [comment]
Seems that I am unable to hide the key while keeping the source code public and hosting the website as is so for the time being I'm just going to leave as is. Maybe a smarter future me will reopen this with a good fix.
