### ISSUE TITLE
Option to replace missing data with average track lengths

### ISSUE THREAD

**Issue by YasashiiDia** [pmcdonough8133/last.timer#12]
It would be great if users had the option to impute (replace) missing track data with the average track length, this would help reduce bias for artists with lots of missing data.

**Comment by pmcdonough8133** [comment]
Added an estimated playtime column on artist view to fill in missing tracks using average track length where available. It doesn't change the current playtime stat nor the does it affect the rank stats but is there to supplement. Closing for now but can reopen if more requests for changes come.
